### ISSUE TITLE
Make solver name in genx_settings file case-insensitive

### ISSUE THREAD

**Issue by gschivley** [GenXProject/GenX#101]
The [docs](https://genxproject.github.io/GenX/dev/data_documentation/#Table-1a:-Summary-of-the-Model-settings-parameters) correctly say that the `Solver` parameter in genx_settings.yml is case sensitive. But the comments in the documentation and the example file give conflicting (and incorrect) examples of how to specify the CLP solver -- one says `CLP`, the other says `clp`, and [the code](https://github.com/GenXProject/GenX/blob/main/src/configure_solver/configure_solver.jl) expects `Clp`. It would be more user-friendly to make the parameter case-insensitive. I'm not sure what the julia method for making a string lowercase is, but in python I'd do something like this:

```py
...
elif solver.lower() == "clp":
...
```

**Comment by cfe316** [comment]
I'm fixing this. Is it not better to do 

`solver = lowercase(solver)` and then just compare with the lowercase versions?

**Comment by cfe316** [comment]
Addressed with PR #103
