### ISSUE TITLE
Remove unused `dfTransCapRes` code

### ISSUE THREAD

**Issue by gschivley** [GenXProject/GenX#102]
In the function`load_cap_reserve_margin_trans` from `load_cap_reserve_margin.jl`, the columns `CapRes_*` are referenced. PowerGenome no longer creates these columns in the Network.csv file and they don't appear to be used anywhere in GenX. Can someone confirm they aren't used and remove them? Also need to remove from the documentation.

**Comment by cfe316** [comment]
At least on the `main` branch, it looks like columns `CapRes_*` *are* in the `src/model/policies/cap_reserve_margin.jl` file, no?

**Comment by cfe316** [comment]
This was addressed by #120. Can the issue be closed?
