### ISSUE TITLE
Possible bug: different comments/formulations but duplicated code in write_net_revenue

### ISSUE THREAD

**Issue by cfe316** [GenXProject/GenX#115]
In write_net_revenue.jl the same expression is written twice for two different values of the `CO2Cap` setting:

```
if setup["CO2Cap"]==1 # Mass-based
    # Cost = sum(sum(emissions of gen y * dual(CO2 constraint[cap]) for z in Z) for cap in setup["NCO2"])
    dfNetRevenue.EmissionsCost[y] += sum(value(EP[:eEmissionsByPlant][y,t]) * inputs["omega"][t] * (-1) * dual(EP[:cCO2Emissions_systemwide][cap])
        for t in 1:T)

elseif setup["CO2Cap"]==2 # Demand + Rate-based
    # Cost = sum(sum(emissions for zone z * dual(CO2 constraint[cap]) for z in Z) for cap in setup["NCO2"])
    dfNetRevenue.EmissionsCost[y] += sum(value(EP[:eEmissionsByPlant][y,t]) * inputs["omega"][t] * (-1) * dual(EP[:cCO2Emissions_systemwide][cap])
        for t in 1:T)
```
the comments are different - one says "Mass based" and one is "Demand + rate based" so it's suspicious to me that the mathematical expressions are the same. I haven't looked into this in detail, so maybe these two *should* really be the same mathematically. If so, it could be good to have a note that these are really the same, and even better, combine the two expressions with `if setup["CO2Cap"] == 1 || setup["CO2Cap"] == 2`.

**Comment by cfe316** [comment]
This may be related to lines in `load_co2_cap.jl` where the expression is the same but the comments are different.

```
  if setup["ParameterScale"] ==1
      inputs_co2["dfMaxCO2Rate"] = Matrix{Float64}(inputs_co2["dfCO2Cap"][:,first_col:last_col])
      # when scaled, the constraint unit is kton, thus the emission rate should be in kton/GWh = ton/MWh
  else
      inputs_co2["dfMaxCO2Rate"] = Matrix{Float64}(inputs_co2["dfCO2Cap"][:,first_col:last_col])
      # when not scaled, the constraint unit is ton/MWh
  end
 ```

**Comment by sambuddhac** [comment]
Thanks @cfe316  .... Taking a look and fixing shortly.

**Comment by cfe316** [comment]
I don't know if somehow the math works out so that it doesn't need to be scaled. As it's written it's confusing. If it's true that it doesn't need to be scaled then the two lines should probably just be combined; no need to have two copies.

**Comment by cfe316** [comment]
Even with the recent vectorizations, this issue stands. Are CO2 being accounted for correctly?

**Comment by xuqingyu** [comment]
They can be combined; but they will disappear if my new carbon cap formulation is added in.

**Comment by xuqingyu** [comment]
This will be fixed in
https://github.com/GenXProject/GenX/pull/216

**Comment by sambuddhac** [comment]
@xuqingyu , is this the PR that you once retracted? Or, is the fix merged already?

**Comment by sambuddhac** [comment]
Because I don't see the duplication any more, it now appears under `if setup["CO2Cap"] >=1`

**Comment by sambuddhac** [comment]
This seems resolved?

**Comment by sambuddhac** [comment]
Reviewing and merging PR #610 will close this issue

**Comment by sambuddhac** [comment]
Merge of PR #610 addresses this.
