### ISSUE TITLE
SCIP version conflicts during instantiation

### ISSUE THREAD

**Issue by fnbillimor** [GenXProject/GenX#121]
Hello, 

I am attempting to install GenX on a Windows system with Julia 1.6.5.  I obtain an error with the installation of the SCIP dependency.  I had previously downloaded SCIP 8.0.0 but received an error that version 8.0.0 is not supported (ERROR1.PNG).  I then removed and reinstalled SCIP version 7.0.3 but received another dependency error, because the installation seems to be looking for the 8.0.0 file (ERROR2.PNG).  Any assistance you may be able to provide here would be really helpful! :) Thanks.
![Error1](https://user-images.githubusercontent.com/98436817/151086956-1029679a-d613-4387-9f45-f1e307aa40b7.png)
![Error2](https://user-images.githubusercontent.com/98436817/151086960-5ba3d072-b0b9-4d45-b463-7f1affeb7048.PNG)

**Comment by sambuddhac** [comment]
Disclaimer: I am unfortunately, not super familiar with working on Windows system.


However, as the SCIP website says, for Windows system, you need to actually download and install the SCIP solver itself (similar to what you would have done, if you were to use a commercial solver like CPLEX or Gurobi) and I would think, that may require you to have compatible versions of the SCIP solver and the JuMP SCIP interface (i.e. SCIP.jl that you are using in your environment). Please let me know, if you already have downloaded and installed SCIP and if you're still having this issue. I can, in the mean time, tag up with one of our team members who work in Windows, and see if we can resolve this issue.

Sam

**Comment by fnbillimor** [comment]
Sam - thank you so much for your quick response.  I had already have downloaded and installed SCIP, so not sure if it is an issue with the interface or something else?

Thanks
Farhad

**Comment by sambuddhac** [comment]
Okay, thanks for letting me know. Let me chat with a couple of my colleagues who use Windows, tomorrow and get back to you ASAP.

**Comment by fnbillimor** [comment]
Thank you @sambuddhac

**Comment by fnbillimor** [comment]
Sam - I am actually not looking to use the SCIP package as a solver (I have Gurobi).   So alternatively If you are able to let me know  which parts in the files to comment out, so that SCIP is not installed and instantiated that would be super helpful.  I tried following the reverse of the instructions provided to include Gurobi, but I think I must be missing something.

Many thanks!
Farhad

**Comment by sambuddhac** [comment]
For now, I have already made these changes. So, just pull and let me know if things are working fine.

**Comment by fnbillimor** [comment]
Thanks @sambuddhac - this works fine! Thanks so much.

**Comment by sambuddhac** [comment]
You're very welcome !!!
