### ISSUE TITLE
Load_generators_data ignores LongDurationStorage=0 (if statement commented out)

### ISSUE THREAD

**Issue by DanielNavia1** [GenXProject/GenX#134]
Hi,

Looking at the code in load_generators_data.jl in the master, there seems to be a typo in line 49. The if statement is commented out, implying the code is looking for LDS resources even "LongDurationStorage" has been disabled in the setup file. This will cause simple generator_data files to fail, as they will not have added the LDS flag. 

Thanks

Daniel

**Comment by DanielNavia1** [comment]
Related to this, in line 33 of Storage_all.jl the reference to the key "STOR_SHORT_DURATION" will fail when "LongDurationStorage" is disabled in the setup file. Eliminating that line altogether solves the issue, but I have not checked if that could create other problems when LongDurationStorage is active.

Thanks

Daniel

**Comment by cfe316** [comment]
Hi Daniel, this was recently addressed on the `Dev` branch by the recent PR #128. 

As for now, the if you're using the `main` branch, the recommended workarounds are:
* Include an `LDS` column of `0`s in `Generators_data.csv`
* Include a line `LongDurationStorage: 0` in `genx_settings.yml`.

**Comment by DanielNavia1** [comment]
Hi

Thanks for that, hadn't seen it. I have changed the title to reflect only the first issue. I will use your suggested workaround.

Thanks

Daniel
