### ISSUE TITLE
UCommit = 0 is broken on Dev

### ISSUE THREAD

**Issue by cfe316** [GenXProject/GenX#140]
The example ISONE_Trizone_FullTimeseries uses the setting UCommit=0. If this is selected, the function `ucommit` is not run and the expression eEmissionsByZone is not created. This expression is then referred to in `co2_cap.jl`, which results in an error during loading.

**Comment by xuqingyu** [comment]
I think this can be closed, there is a new emissions.jl and a subsequent update to emissions.jl with co2.jl will follow. Both will fix this.
