### ISSUE TITLE
Understanding Flow of Julia

### ISSUE THREAD

**Issue by iAnkiit** [GenXProject/GenX#156]
Could someone please help me out in understanding flow of GenX model ? 
I am unable to use GenX.

**Comment by sambuddhac** [comment]
Hi @iAnkiit , I would suggest going through the detailed GenX documentation on top of the README, here:  https://genxproject.github.io/GenX/dev/ followed by the deeper dive here (if you want to pursue this): https://genx.mit.edu/ . Please let me know once you go through these, if you have more questions.
