### ISSUE TITLE
Update Gurobi package 0.11.0 to use Gurobi 9.5

### ISSUE THREAD

**Issue by dharik13** [GenXProject/GenX#161]
Most latest version of Gurobi includes some valuable features including representation of quadratic terms in the model that are automatically handled by Gurobi. However, for that we need to update Gurobi.jl package version to be 0.10.3 or higher. This creates some conflicts with MathOptInterface versions that need to be addressed.

**Comment by GenXProject** [comment]
PR #179 now addresses this with a new file, Guide_to_Project.toml
