### ISSUE TITLE
 Protect against an empty FLEX or STOR_ALL on main

### ISSUE THREAD

**Issue by cfe316** [GenXProject/GenX#168]
`write_reserve_margin_revenue` can fail if FLEX or STOR_ALL is empty.

This was fixed on `Dev` but I forgot to include https://github.com/GenXProject/GenX/pull/147/commits/0a99ab53a99bd5b0961aff66f0aaff4a96e16229 in my `vectorizeMain` PR.

**Comment by cfe316** [comment]
This is addressed by #169

**Comment by GenXProject** [comment]
This is now addressed by PR #179

**Comment by cfe316** [comment]
This is now fixed on main.
