### ISSUE TITLE
Argument mismatch on Dev Branch

### ISSUE THREAD

**Issue by glarange** [GenXProject/GenX#171]
Hi Sam,

Argument mismatch I'm facing on the dev branch. Functions that are being called on the 'write_output.jl' that are mismatched with the respective function files.

Regards,
Gui

ERROR: LoadError: MethodError: no method matching write_capacity_value(::String, ::String, ::Dict{Any, Any}, ::Dict{Any, Any}, ::DataFrames.DataFrame, ::DataFrames.DataFrame, ::DataFrames.DataFrame, ::DataFrames.DataFrame)
Closest candidates are:
  write_capacity_value(::AbstractString, ::AbstractString, ::Dict, ::Dict, ::JuMP.Model) at ~/Google Drive/GenX-Dev/src/write_outputs/capacity_reserve_margin/write_capacity_value.jl:17
Stacktrace:
 [1] macro expansion
   @ ./timing.jl:299 [inlined]
 [2] write_outputs(EP::JuMP.Model, path::String, setup::Dict{Any, Any}, inputs::Dict{Any, Any})
   @ GenX ~/Google Drive/GenX-Dev/src/write_outputs/write_outputs.jl:177
 [3] top-level scope
   @ ./timing.jl:299
 [4] include(fname::String)
   @ Base.MainInclude ./client.jl:451
 [5] top-level scope
   @ REPL[3]:1
in expression starting at /Users/dtsadmin/Google Drive/GenX-Dev/Example_Systems/SmallNewEngland/OneZone/Run.jl:74

**Comment by cfe316** [comment]
This can now be addressed by #175 .

**Comment by sambuddhac** [comment]
This has been fixed on Dev
