### ISSUE TITLE
When UCommit = 1 write_storagedual is called even if there is not storage.

### ISSUE THREAD

**Issue by cfe316** [GenXProject/GenX#172]
On `main`, UCommit=1 leads to `write_storagedual` being called, but if there is no storage then `:cSocBalInterior` has not been created and that function results in an error.

I'd suggest that this be fixed by wrapping `write_storagedual` in `if !isempty(inputs["STOR_ALL"])` or similar.

**Comment by xuqingyu** [comment]
@sambuddhac I believe this is still an open issue.

**Comment by cfe316** [comment]
This has been fixed by #226
