### ISSUE TITLE
write_rsv will fail because 'sep' is not defined

### ISSUE THREAD

**Issue by cfe316** [GenXProject/GenX#189]
I haven't tried this explicitly, but I'm fairly sure any call to `write_rsv` will fail because `sep` has not been defined in that function. The best practice here is to use `joinpath`.

**Comment by cfe316** [comment]
Same thing in `write_power`, `write_nse`, `write_power_balance` and other files. I'll upload a PR to Dev to fix these.

**Comment by sambuddhac** [comment]
Thanks @cfe316 . Seems one of the merges hampered some of these. Please send a PR. I will go on merging those for 0.3.1.

**Comment by cfe316** [comment]
This is addressed by #191 .

**Comment by cfe316** [comment]
This was fixed by the recent merge of `Dev`.
