### ISSUE TITLE
README mentions both JuMP v0.21.3 and v0.21.4

### ISSUE THREAD

**Issue by danielolsen** [GenXProject/GenX#19]
> GenX.jl runs on Julia v1.3.0 and JuMP v0.21.3...
on l. 26

> Note that if you have not already installed the required Julia packages, you are using a version of JuMP other than v0.21.4, or you do not have a valid Gurobi license on your host machine, you will receive an error message and Run.jl will not run to completion.
on l. 70 (and 78)

Looking at Project.toml, it looks like all references should be to 0.21.3, unless there's different version compatibility when using Gurobi/CPLEX? I didn't see `the relevant lines in the [deps] and [compat] in the Project.toml file` to be able to uncomment for Gurbobi/CPLEX (l. 73).

**Comment by sambuddhac** [comment]
Hey @danielolsen 

Here are the relevant UUID's and minimum compatible version numbers. Sorry. it seems we needed to delete it for some compatibility issues. I will check with Jesse and the rest of the team and if it's all-clear put the commented lines back again. For now, please use these on own own to the Project.toml:

[deps]
#CPLEX = "a076750e-1247-5638-91d2-ce28b192dca0"
#Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"

[compat]
#CPLEX = "0.6.1"
#Gurobi = "0.7.6"

Will also take up the JuMP version issue with the team. The 21.3 that shows up in the Project.toml is the minimum one for compatibility. But, when we ran through the instantiation at our end with the Method2 to get the UUIDs (which creates the Manifest.toml as well), it seems 21.4 is the then latest and compatible version the environment creation system at Julia grabbed. Please correct me if I am wrong. Looking at the results, this is what dawns in my mind. I am still riding on the learning curve on details of how exactly Julia environments are created and not all the things are yet super clear to me.

Thanks and please let me know if you have further questions.

**Comment by danielolsen** [comment]
I think `JuMP = "0.21.3"` in Project.toml will resolve to any JuMP version `v0.21.x` where `x >= 3`. See https://pkgdocs.julialang.org/stable/compatibility/#Version-specifier-format-1

If you want exactly `0.21.3`, it can be specified as `JuMP = "= 0.21.3"`. Or if the current flexibility is okay (`[0.21.3, 0.22.0)`), then I think it would help to remove the references to `v0.21.4` in the README, and just mention 'incompatible version of JuMP' or something like that.

**Comment by sambuddhac** [comment]
Corrected in the documentation. Closing the issue.
