### ISSUE TITLE
Key 'Multistage' is not set by default

### ISSUE THREAD

**Issue by cfe316** [GenXProject/GenX#190]
When I run a test case, e.g. SmallNewEngland/test_Down_Time, 

I get the error `LoadError: KeyError: key "MultiStage" not found` during the configuration stage.

**Comment by cfe316** [comment]
Ah, I think this test case was included by accident. 

This particular test case doesn't call configure_settings in its Run.jl. We should consider creating a canonical run script with a function like `rungenxcase(path::AbstractString)` so that `Run.jl` need only contain `import GenX; rungenxcase(".")`

**Comment by xuqingyu** [comment]
Thanks for pointing this out, @cfe316. I will close this, but if anyone looked this thread, they know that we should use configure_settings(). Your suggestion is similar like to have a Run.jl as a function in `src/` folder.
