### ISSUE TITLE
Suggestion: using setup instead of setup["something"] in functions

### ISSUE THREAD

**Issue by xuqingyu** [GenXProject/GenX#194]
Maybe instead of using setup["something"] in the function argument, we simply use setup to untify the code.
This is has an advantage that everything in the setup can be read by the function. Plus the order of the argument won't matter anymore.  It seems dangerous if order of argument differs between
when it is called in generate_model.jl 
when it is defined.

**Comment by cfe316** [comment]
This is a good idea! This will make the interfaces smaller and easier to maintain in the future. I'm working on it now.

**Comment by cfe316** [comment]
This was addressed by #197 and has now been merged to `main`; this issue can be closed.
