### ISSUE TITLE
Any reason to setup a new env instead of setting up everything in the Project.toml?

### ISSUE THREAD

**Issue by jiweiqi** [GenXProject/GenX#2]
https://github.com/GenXProject/GenX/blob/2a264cc1ac5b17e96c6f31718a014784121df140/julenv.jl#L17-L37

Most of my experience is setting those dependences in the `Project.tml` so that they will be installed with GenX together. Any consideration to create a new environment?

**Comment by jiweiqi** [comment]
Seems the current approach is better for creating a new environment.

**Comment by sambuddhac** [comment]
Awesome !!!! Please let us know in case of any problem. Thanks and your contribution is highly valued by the GenX team.
