### ISSUE TITLE
write_power_balance

### ISSUE THREAD

**Issue by xuqingyu** [GenXProject/GenX#201]
It looks like sep is not an argument anymore but is still used in the write_csv function at the end of the file.

**Comment by xuqingyu** [comment]
this seems not to be an unique issue to write_power_balance.

**Comment by GenXProject** [comment]
Will set up a PR correcting this. Thanks !!!

**Comment by cfe316** [comment]
This is the same as #189 and has been fixed on Dev for a few days now.

**Comment by cfe316** [comment]
This was fixed by the recent merge of `Dev`; this issue can be closed.
