### ISSUE TITLE
Error when Writing Output of SmallEngland OneZone example

### ISSUE THREAD

**Issue by pescortell** [GenXProject/GenX#21]
Windows 10 Pro
Version : 10.0.19042 Build 1902
Julia 1.6.1
CSV v0.6.1
Cbc v0.8.0
Clp v0.8.4
Clustering v0.14.2
Combinatorics v1.0.2
DataFrames v0.20.2
DataStructures v0.17.20
Distances v0.10.3
Documenter v0.24.11
DocumenterTools v0.1.11
GLPK v0.14.12
Ipopt v0.6.5
JuMP v0.21.4
MathProgBase v0.7.8
StatsBase v0.33.8
YAML v0.4.7
Dates
LinearAlgebra

How to Replicate?
1. Julia navigates to the root file of the cloned GenX project. 
2. julia> include(“<path to your case>/Run.jl”)
3. And then I get the error below

### Error report

ERROR: LoadError: MethodError: no method matching ndims(::Type{DataFrames.LazyNewColDataFrame{Int64}})
Closest candidates are:
  ndims(::LinearAlgebra.UniformScaling) at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\LinearAlgebra\src\uniformscaling.jl:87
  ndims(::CartesianIndices) at multidimensional.jl:356
  ndims(::DataFrames.AbstractDataFrame) at C:\Users\PereEscortell\.julia\packages\DataFrames\S3ZFo\src\abstractdataframe\abstractdataframe.jl:29
...
 Stacktrace:
 [1] Base.Broadcast.BroadcastStyle(#unused#::Type{DataFrames.LazyNewColDataFrame{Int64}})
   @ Base.Broadcast .\broadcast.jl:103
 [2] combine_styles(c::DataFrames.LazyNewColDataFrame{Int64})
   @ Base.Broadcast .\broadcast.jl:420
 [3] combine_styles(c1::DataFrames.LazyNewColDataFrame{Int64}, c2::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{0}, Nothing, typeof(identity), Tuple{Float64}})
   @ Base.Broadcast .\broadcast.jl:421
 [4] materialize!(dest::DataFrames.LazyNewColDataFrame{Int64}, bc::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{0}, Nothing, typeof(identity), Tuple{Float64}})
   @ Base.Broadcast .\broadcast.jl:891
 [5] write_power(path::String, sep::String, inputs::Dict{Any, Any}, setup::Dict{Any, Any}, EP::JuMP.Model)
   @ GenX C:\Users\PereEscortell\.julia\environments\GenX\GenX\src\write_outputs\write_power.jl:46
 [6] write_outputs(EP::JuMP.Model, path::String, setup::Dict{Any, Any}, inputs::Dict{Any, Any})
   @ GenX C:\Users\PereEscortell\.julia\environments\GenX\GenX\src\write_outputs\write_outputs.jl:63
 [7] top-level scope
   @ C:\Users\PereEscortell\.julia\environments\GenX\GenX\Example_Systems\SmallNewEngland\Onezone\Run.jl:73
 [8] include(fname::String)
   @ Base.MainInclude .\client.jl:444
 [9] top-level scope
   @ REPL[130]:1
in expression starting at C:\Users\PereEscortell\.julia\environments\GenX\GenX\Example_Systems\SmallNewEngland\Onezone\Run.jl:73

**Comment by sambuddhac** [comment]
Hi @pescortell, 

So, first of all: I see that you're using Julia 1.6 series. Unfortunately, so far, the way we designed GenX, it works only with the 1.3.x series. So, I would highly recommend reverting your Julia version back to the 1.3.x series. 

Secondly: You got to "activate ." followed by "instantiate" if you're running for the first time and then type "st" from the "(GenX) pkg>" package prompt (that you go to, by typing "]" at the "julia>" REPL prompt, which you can open by double-clicking on the Julia icon, if you're on Windows machine). It's always a good idea to do a "pwd()" in the julia> prompt, after you open the Julia kernel, to see where exactly you are. If you're at any where other than GenX/ folder, type cd(<path to GenX folder, depending on where you are>) in the julia> prompt. Then follow the steps outlined at the beginning of this paragraph. 

Once you have checked that you have all the dependencies installed, while you're at the GenX/ folder level (which is the GenX root), you need to come back to julia> prompt from the (GenX) pkg> prompt by hitting the backspace key. Now at the julia> prompt, you should type "include("Example_Systems\SmallNewEngland\Onezone\Run.jl")" and hit enter. Remember: when you execute this command, you're still at GenX root level and inside the julia> REPL. And that's the path to your case from where you're currently. 

Alternatively, if you want to run GenX following method 2, you need to uncomment some lines of the code and follow a slightly different route (please refer to the documentation or the README). Please let me know, if that helped resolve your problem. If not, please send me some screenshots, which might help me gain a grip on your issue. 

Good luck !!!

**Comment by cappuccinocosmico** [comment]
I had the same same error message and downgrading to julia 1.3.1 https://julialang.org/downloads/oldreleases/ solved the problem

**Comment by pescortell** [comment]
I'm clearly doing something wrong when trying to run this simple example... I have installed julia 1.3.1, created a new environment for GenX, cloned the repository, activate the environment, and then trying to run the model. I had lots of errors in relation of missing packages. I've installed all the required packages and now I am getting a more complicated error which I cannot figure out how to fix. 


See below: 

julia> include("c:/Users/PereEscortell/julia1.3/environments/GenXEnv/GenX/GenX/Example_Systems/SmallNewEngland/Onezone/Run.jl")
Loading packages
Time Series Data Already Clustered.
Configuring Solver
Loading Inputs
Reading Input CSV Files
**ERROR: LoadError: BoundsError: attempt to access 0-element Array{Int64,1} at index [1]**
Stacktrace:
 [1] getindex at .\array.jl:744 [inlined]
 [2] load_network_data(::Dict{Any,Any}, ::String, ::String, ::Dict{Any,Any}) at c:\Users\PereEscortell\julia1.3\environments\GenXEnv\GenX\GenX\src\load_inputs\load_network_data.jl:35
 [3] load_inputs(::Dict{Any,Any}, ::String) at c:\Users\PereEscortell\julia1.3\environments\GenXEnv\GenX\GenX\src\load_inputs\load_inputs.jl:45
 [4] top-level scope at c:\Users\PereEscortell\julia1.3\environments\GenXEnv\GenX\GenX\Example_Systems\SmallNewEngland\Onezone\Run.jl:58
 [5] include at .\boot.jl:328 [inlined]
 [6] include_relative(::Module, ::String) at .\loading.jl:1105
 [7] include(::Module, ::String) at .\Base.jl:31
 [8] include(::String) at .\client.jl:424
 [9] top-level scope at REPL[72]:1
in expression starting at c:\Users\PereEscortell\julia1.3\environments\GenXEnv\GenX\GenX\Example_Systems\SmallNewEngland\Onezone\Run.jl:58
caused by [exception 10]

**Comment by sambuddhac** [comment]
Hi @pescortell 

I am happy to take a look and help you out. Would you be willing to set up a zoom session?

**Comment by pescortell** [comment]
Hi @sambuddhac you're offering is much appreciated. I have tried again and this time I managed to run the example. I need a crash course on Julia and setting up environments. Thanks again!

**Comment by sambuddhac** [comment]
Awesome !!! I am going to put up some pictures along with revised instructions on README and documentation. That should be good to help you. Please let me know, if you have further questions.
