### ISSUE TITLE
Output reliabilty.csv is spelled incorrectly; needs an extra 'i'

### ISSUE THREAD

**Issue by cfe316** [GenXProject/GenX#211]
Noticed this just now. Fixing it could help us achieve energy indendence ;)

On the down side, updating this would break anyone's scripts that rely on it.

**Comment by cfe316** [comment]
I can fix it. But separate issues should be separate commits and PRs.

**Comment by xuqingyu** [comment]
Done by @cfe316's https://github.com/GenXProject/GenX/pull/217
