### ISSUE TITLE
Wrong name file

### ISSUE THREAD

**Issue by pescortell** [GenXProject/GenX#22]
In the Requirements section of the Documentation, it refers to the file " **juliaenv.jl** in the parent directory lists all of the packages and their versions needed to run GenX " . I believe this file is now named "julenv.jl".

**Comment by sambuddhac** [comment]
That should be julenv.jl and not juliaenv.jl. That's a typo. Taking note to correct it. Thanks a lot !!!

**Comment by sambuddhac** [comment]
Corrected. Closing issue.
