### ISSUE TITLE
Possibly unnecessary argument in function generate_model?

### ISSUE THREAD

**Issue by sambuddhac** [GenXProject/GenX#232]
Presently, the function generate_model within `GenX/src/model/generate_model.jl` is of the form `generate_model(setup::Dict,inputs::Dict,OPTIMIZER::MOI.OptimizerWithAttributes, modeloutput = nothing)` where it seems the `modeloutput ` is used to decide where exactly the lp file will be output. But, I am wondering, if this is super important. I mean, why can't it be in the default option `pwd()` always, which will, in this case, be the particular example system we are running. It's always possible to modify the .gitignore to just not include the lpfile in the commits.

**Comment by cfe316** [comment]
The lp file has one line per variable or constraint or expression, including every index of array variables etc. It would be hundreds of megabytes for some of my runs. Outputting it would be wasted space and time.On Jul 8, 2022 8:36 PM, "Chakrabarti, Sambuddha (Sam)" ***@***.***> wrote:
Presently, the function generate_model within GenX/src/model/generate_model.jl is of the form generate_model(setup::Dict,inputs::Dict,OPTIMIZER::MOI.OptimizerWithAttributes, modeloutput = nothing) where it seems the modeloutput  is used to decide where exactly the lp file will be output. But, I am wondering, if this is super important. I mean, why can't it be in the default option pwd() always, which will, in this case, be the particular example system we are running. It's always possible to modify the .gitignore to just not include the lpfile in the commits.

**Comment by sambuddhac** [comment]
PR #233 addresses this

**Comment by cfe316** [comment]
My bad! I understand this issue and fix now.

**Comment by sambuddhac** [comment]
No worries.

**Comment by cfe316** [comment]
This was addressed in the 0.3.1 patch.
