### ISSUE TITLE
Gurobi Settings

### ISSUE THREAD

**Issue by wilson-ricks** [GenXProject/GenX#26]
configure_gurobi.jl does not include "Crossover" in the settings listed at line 68. This means that changing the "Crossover" tag in gurobi_settings.yml currently does nothing.

**Comment by GenXProject** [comment]
Thanks @wilson-ricks  for pointing this out. This should be resolved in the latest commit.

**Comment by sambuddhac** [comment]
@wilson-ricks can you please check now. I think the issue is resolved, as of yesterday, @GenXProject ?
