### ISSUE TITLE
Dependency Issue with Gurobi.jl Version

### ISSUE THREAD

**Issue by lanesmith** [GenXProject/GenX#264]
In version 0.3.1, it appears that the required version of `MathOptInterface.jl` (1.6.1) does not satisfy the dependency requirement for the specified version of `Gurobi.jl` (0.9.14). That version of `Gurobi.jl` requires `MathOptInterface.jl` to be ~0.9.19.

**Comment by cfe316** [comment]
Thanks for flagging this. Rather than push MathOptInterface backward, can we push `Gurobi.jl` forward? It looks like the newest version, `0.11.3` is compatible.

**Comment by cfe316** [comment]
This is addressed by #268 .

**Comment by lanesmith** [comment]
Thanks!

**Comment by cfe316** [comment]
Reopening because issue has not yet been fixed.

**Comment by sambuddhac** [comment]
Just rebased and merged on develop branch.
