### ISSUE TITLE
Constant startup cost

### ISSUE THREAD

**Issue by ADC27** [GenXProject/GenX#273]
Startup cost is calculated as a function of time i.e dependent on fuel cost which is varying with time which can be seen in this line from load_generators_data.jl

inputs_gen["C_Start"][g,:] = inputs_gen["dfGen"][g,:Cap_Size] * (fuel_costs[fuel_type[g]] .* start_fuel[g] .+ start_cost[g])

When the same cost is used to obtain startup cost of generation by multiplying with the number of starts every hour, it is taken as a constant i.e, only the first element of the dataframe/matrix is used,  which can be seen from this line from ucommit.jl

@expression(EP, eCStart[y in COMMIT, t=1:T],(inputs["omega"][t]*inputs["C_Start"][y]*vSTART[y,t]))

Is this a mistake or Is there any particular reason to take only the first element of startup cost. 

I believe this variable should be iterated like ["C_Start"][y,t]:
@expression(EP, eCStart[y in COMMIT, t=1:T],(inputs["omega"][t]*inputs["C_Start"][y,t]*vSTART[y,t]))

**Comment by xuqingyu** [comment]
@ADC27 thanks, good point
@sambuddhac @JesseJenkins I think this is an error.

**Comment by sambuddhac** [comment]
Ok, will make the necessary code modification.

**Comment by sambuddhac** [comment]
PR #278 fixes this. The earlier faulty PR (PR #275) is now removed. @JesseJenkins @xuqingyu @cfe316 @dharik13 I have assigned you as reviewers. You can now review and let me know in case of questions.

**Comment by sambuddhac** [comment]
This issue is now fixed on main
