### ISSUE TITLE
ERROR: Unsatisfiable requirements detected for package OrdinaryDiffEq 

### ISSUE THREAD

**Issue by matteodefelice** [GenXProject/GenX#274]
I have just tried to install `GenX` on my WSL (Ubuntu 20.04).
I have cloned the repository and installed Julia with anaconda. 
Then I followed the steps specified in the Readme:
- entered in `GenX` folder
- typed `julia --project=.`
- then `instantiate` 

Then I receive this error: 
```
(GenX) pkg> instantiate
ERROR: Unsatisfiable requirements detected for package OrdinaryDiffEq [1dea7af3]:
 OrdinaryDiffEq [1dea7af3] log:
 ├─possible versions are: 4.0.0-5.68.0 or uninstalled
 └─restricted to versions 6.20.0-6 by GenX [5d317b1e] — no versions left
   └─GenX [5d317b1e] log:
     ├─possible versions are: 0.3.1 or uninstalled
     └─GenX [5d317b1e] is fixed to version 0.3.1
```
If I type `st` I get:
```
(GenX) pkg> st
Project GenX v0.3.1
Status `/mnt/c/Users/matte/OneDrive/local/work/GenX/Project.toml`
  [6e4b80f9] BenchmarkTools
  [336ed68f] CSV
  [9961bab8] Cbc
  [e2554f3b] Clp
  [aaaa29a8] Clustering
  [861a8166] Combinatorics
  [a93c6f00] DataFrames
  [864edb3b] DataStructures
  [b4f34e82] Distances
  [87dc4568] HiGHS
  [4076af6c] JuMP
  [b8f27783] MathOptInterface
  [1dea7af3] OrdinaryDiffEq
  [731186ca] RecursiveArrayTools
  [82193955] SCIP
  [2913bbd2] StatsBase
  [ddb6d928] YAML
  [ade2ca70] Dates
  [37e2e46d] LinearAlgebra
  [9a3f8284] Random
  [10745b16] Statistics
```
I had the same issue with Julia 1.6, 1.7 and 1.8.
Any ideas on how to fix this?

**Comment by sambuddhac** [comment]
@matteodefelice , thanks for flagging. I am currently testing it. Will circle back at you as soon as I fix.

**Comment by GenXProject** [comment]
@matteodefelice , can you once try to run GenX from the `Develop` branch and report to me what you get? If the problem still persists, I will resolve it on Develop first, and then merge into main with the next patch release and circle back at you.

**Comment by matteodefelice** [comment]
I get the same identical error.

**Comment by cfe316** [comment]
Could you try deleting OrdinaryDiffEq entirely from the requirements? I'm fairly certain that we don't actually need it.

**Comment by matteodefelice** [comment]
If I remove it the error becomes:
```
ERROR: Unsatisfiable requirements detected for package StatsBase [2913bbd2]:
```

**Comment by sambuddhac** [comment]
@matteodefelice did you do a fresh build (i.e. delete the old Manifest.toml) and also delete the using `OrdinaryDiffEq` line from GenX.jl before building? Also, when you're trying to run from either the main or the Develop branch, please do a git pull first to get all the recent changes, and then do a fresh build. Please let me know, if that works. If it doesn't, then I'll spend some more time to see where things might be going wrong.

**Comment by matteodefelice** [comment]
unfortunately, it doesn't. I have tried both in `main` and in `Develop`, editing both the files but nothing.

**Comment by sambuddhac** [comment]
PR # 282 will fix this issue, when merged

**Comment by sambuddhac** [comment]
This issue is now fixed.
