### ISSUE TITLE
Removing or adding the time domain reduction component of GenX

### ISSUE THREAD

**Issue by kalebsm** [GenXProject/GenX#285]
Hello, 
The SmallNewEngland/OneZone example system uses the time reduction techniques described in the documentation. I tried to remove the time-reduction component by changing time_domain_reduction to 0 (from 1) in GenX_settings.yml, because I want to print out results for 8760 hours instead. The result I get however is unsatisfactory as the prices returned from running this are 57252 until the t168. Since 168 is the TimestepsPerRepPeriod indicated for the time reduction step, I suspect there are more components that I need to change. Could anyone describe what else needs to be updated to switch a model from using the Time Domain Reduction with one that does not?

Thanks,
Kaleb

**Comment by cfe316** [comment]
Hi Kaleb,

Could you please confirm which branch (and commit) you're using? What operating system, and what solver?

I'm able to reproduce this bug with the default settings using commit `ed826de`. 
Even after turning off Unit Commitment (setting `UCommit=0`) and setting `Crossover=0` in my solver's settings. I still see that the first 168h of prices are finite and after that is bogus (`-Inf` or similar).

@sambuddhac looking at `write_price.jl`, there's a step where we divide by `inputs["omega"]`. If for some reason it's now only one RepresentativePeriod long that could would be why we're having `-Inf`s.

**Comment by cfe316** [comment]
In `genx_settings.yml`, `OperationWrapping` should be set to `0` since `TimeDomainReduction` is off. This fixes the issue.

... We should probably have some sort of warning for misconfigured settings.

**Comment by sambuddhac** [comment]
Oops !!! My apologies for being late to the party. But, as Jacob mentioned, ... setting the OperationsWrapping to 0 resolves the issue.

**Comment by kalebsm** [comment]
Changing the OperationWrapping to 0 resolves the issue on my end too. Thanks you both for your responsiveness.


For completeness, the details are:

commit e294356 (HEAD -> main, origin/main, origin/HEAD)
Date:   Thu Jun 23 12:19:40 2022 -0400
OS: Windows
Solver: clp
