### ISSUE TITLE
Error in running onezone example

### ISSUE THREAD

**Issue by jiweiqi** [GenXProject/GenX#3]
https://github.com/GenXProject/GenX/blob/2a264cc1ac5b17e96c6f31718a014784121df140/Example_Systems/SmallNewEngland/OneZone/Run_test.jl#L74

```Julia
User-callback calls 1905, time in user-callback 0.01 sec
LP solved for primal
Writing Output
ERROR: LoadError: MethodError: no method matching ndims(::Type{DataFrames.LazyNewColDataFrame{Int64}})
Closest candidates are:
  ndims(::Type{MutableArithmetics.Zero}) at C:\Users\Weiqi Ji\.julia\packages\MutableArithmetics\6pKCK\src\rewrite.jl:89
  ndims(::Base.Generator) at generator.jl:53
  ndims(::Number) at number.jl:67
  ...
Stacktrace:
 [1] Base.Broadcast.BroadcastStyle(::Type{DataFrames.LazyNewColDataFrame{Int64}}) at .\broadcast.jl:103
 [2] combine_styles(::DataFrames.LazyNewColDataFrame{Int64}) at .\broadcast.jl:420
 [3] combine_styles(::DataFrames.LazyNewColDataFrame{Int64}, ::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{0},Nothing,typeof(identity),Tuple{Float64}}) at .\broadcast.jl:421
 [4] materialize!(::DataFrames.LazyNewColDataFrame{Int64}, ::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{0},Nothing,typeof(identity),Tuple{Float64}}) at .\broadcast.jl:845
 [5] write_power(::String, ::String, ::Dict{Any,Any}, ::Dict{Any,Any}, ::Model) at C:\Users\Weiqi Ji\Dropbox (MIT)\Project\OpenEnergy\GenX\GenX\src\write_outputs\write_power.jl:46
 [6] write_outputs(::Model, ::String, ::Dict{Any,Any}, ::Dict{Any,Any}) at C:\Users\Weiqi Ji\Dropbox (MIT)\Project\OpenEnergy\GenX\GenX\src\write_outputs\write_outputs.jl:63
 [7] top-level scope at C:\Users\Weiqi Ji\Dropbox (MIT)\Project\OpenEnergy\GenX\GenX\Example_Systems\SmallNewEngland\OneZone\Run_test.jl:74
 [8] include(::String) at .\client.jl:457
 [9] top-level scope at REPL[33]:1
in expression starting at C:\Users\Weiqi Ji\Dropbox (MIT)\Project\OpenEnergy\GenX\GenX\Example_Systems\SmallNewEngland\OneZone\Run_test.jl:74
```

**Comment by jiweiqi** [comment]
Same issue for another example with var bins
```Julia
Loading packages
[ Info: Precompiling GenX [top-level]
Clustering Time Series Data...
Reading Input CSV Files
Network.csv Successfully Read!
Load_data.csv Successfully Read!
Fuels_data.csv Successfully Read!
Generators_data.csv Successfully Read!
Generators_variability.csv Successfully Read!
CO2_cap.csv Successfully Read!
CSV Files Successfully Read In From C:\Users\Weiqi Ji\Dropbox (MIT)\Project\OpenEnergy\GenX\GenX\Example_Systems\SmallNewEngland\OneZone_3VREBin\
ERROR: LoadError: MethodError: no method matching ndims(::Type{DataFrames.LazyNewColDataFrame{Symbol}})
Closest candidates are:
  ndims(::Type{MutableArithmetics.Zero}) at C:\Users\Weiqi Ji\.julia\packages\MutableArithmetics\6pKCK\src\rewrite.jl:89
  ndims(::Base.Generator) at generator.jl:53
  ndims(::Number) at number.jl:67
  ...
Stacktrace:
 [1] Base.Broadcast.BroadcastStyle(::Type{DataFrames.LazyNewColDataFrame{Symbol}}) at .\broadcast.jl:103
 [2] combine_styles(::DataFrames.LazyNewColDataFrame{Symbol}) at .\broadcast.jl:420
 [3] combine_styles(::DataFrames.LazyNewColDataFrame{Symbol}, ::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(+),Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(div),Tuple{UnitRange{Int64},Float64}},Int64}}) at .\broadcast.jl:421
 [4] materialize!(::DataFrames.LazyNewColDataFrame{Symbol}, ::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(+),Tuple{Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,typeof(div),Tuple{UnitRange{Int64},Float64}},Int64}}) at .\broadcast.jl:845
 [5] cluster_inputs(::String, ::Dict{Any,Any}, ::Bool) at C:\Users\Weiqi Ji\Dropbox (MIT)\Project\OpenEnergy\GenX\GenX\src\time_domain_reduction\time_domain_reduction.jl:548
 [6] cluster_inputs(::String, ::Dict{Any,Any}) at C:\Users\Weiqi Ji\Dropbox (MIT)\Project\OpenEnergy\GenX\GenX\src\time_domain_reduction\time_domain_reduction.jl:458
 [7] top-level scope at C:\Users\Weiqi Ji\Dropbox (MIT)\Project\OpenEnergy\GenX\GenX\Example_Systems\SmallNewEngland\OneZone_3VREBin\Run_test.jl:42
 [8] include(::String) at .\client.jl:457
 [9] top-level scope at REPL[12]:1
in expression starting at C:\Users\Weiqi Ji\Dropbox (MIT)\Project\OpenEnergy\GenX\GenX\Example_Systems\SmallNewEngland\OneZone_3VREBin\Run_test.jl:39
```

**Comment by jiweiqi** [comment]
Details about my environment

Operating system: Windows 10
Julia packages
```Julia
Status `C:\Users\Weiqi Ji\Dropbox (MIT)\Project\OpenEnergy\GenX\GenX\Example_Systems\SmallNewEngland\OneZone_3VREBin\GenXJulEnv\Project.toml`
  [a076750e] CPLEX v0.6.1
  [336ed68f] CSV v0.6.0
  [e2554f3b] Clp v0.8.1
  [aaaa29a8] Clustering v0.14.2
  [861a8166] Combinatorics v1.0.2
  [a93c6f00] DataFrames v0.20.2
  [864edb3b] DataStructures v0.17.20
  [b4f34e82] Distances v0.10.2
  [e30172f5] Documenter v0.24.7
  [35a29f4d] DocumenterTools v0.1.9
  [2e9cd046] Gurobi v0.7.6
  [4076af6c] JuMP v0.21.3
  [fdba3010] MathProgBase v0.7.8
  [2913bbd2] StatsBase v0.33.0
  [ddb6d928] YAML v0.4.3
  [37e2e46d] LinearAlgebra
```

**Comment by jiweiqi** [comment]
@sambuddhac , apologize for pinging you here, after some debugging, I have a question about the index value ``:Group` in
https://github.com/GenXProject/GenX/blob/1ad1ccf26adb3142710daeb594e03a1f980ac9a5/src/time_domain_reduction/time_domain_reduction.jl#L548

As seen in the bug trace, the error comes from this line of code. I suspect that's because the variable `:Group` is not defined anywhere. Any thoughts on it?

**Comment by sambuddhac** [comment]
Hi 

Apologies for the late reply. Was taking the long weekend a bit easy. Back to work now and will address your concerns one by one. Thanks a lot !!!

Sam

**Comment by jiweiqi** [comment]
Hi @sambuddhac , sure, no problem. I am new to DataFrame.jl, so that I am learning it. So far, I guess the issue can be fixed by

` InputData[:, :Group] = (1:Nhours) .÷ (TimestepsPerRepPeriod+0.0001) .+ 1 `

since here we are adding a new column that doesn't exist yet. So removing the elemental operation.

**Comment by sambuddhac** [comment]
Please go ahead and place a PR. I will go through this one as well as your previous PR and the issues you opened. If I have doubts, then I can take it up with the rest of the GenX team over our meeting tomorrow. 

Thanks a lot and we highly appreciate your contribution !!!

Sam

**Comment by jiweiqi** [comment]
Hi Sam,

I would be happy to contribute. There are might several similar issues in the code for now. I would like to work with someone that is familiar with this part to fix them together. Those are essential for the examples to be successfully executed.

P.S. all of the errors would be relevant to creating/mutating the DataFrame, I guess.

Weiqi

**Comment by jiweiqi** [comment]
Hi @sambuddhac , a quick question on how do you recompile code?

 For example, after changing the source code, I have to restart the repl and redo everything to check if the bug is fixed. Normally, we should be able to use Revise.jl for fast testing.

**Comment by sambuddhac** [comment]
As of now, I am doing exactly how you're doing it. I know of Revise.jl but haven't used it yet. I will try to incorporate Revise.jl within GenX today. If you're already well-versed with it, can you please place a PR to include Revise.jl in the current code? That would be a great contribution !!!

Sam

**Comment by jiweiqi** [comment]
Aha, I am also new to Revise.jl and I heard it from someone else. I am trying it now.

**Comment by jiweiqi** [comment]
@sambuddhac , I am wondering do you also have this issue on your side? If the issue is specific to my computer, I can try another computer.

**Comment by sambuddhac** [comment]
Hey Weiqi, 

Can you please remind me once again the particular problem. I might also ask you to wait a little longer, since we are making bunch of modifications currently. I'll once again get back to you on some details in about a couple days. 

Thanks a lot !!!

Sam

**Comment by jiweiqi** [comment]
Thanks for letting me know. The particular problem is detailed at https://github.com/GenXProject/GenX/issues/3#issuecomment-851611811

**Comment by jiweiqi** [comment]
This is to let you know after changing the Julia version from 1.5.3 to 1.3, and switching from my Windows 10 to a Ubuntu system, the example now works well. Although I still don't know why it doesn't work on my Windows PC. But I suspect it only happens on my Windows PC, probably not a common issue.

**Comment by sambuddhac** [comment]
Sorry Weiqi for the trouble with the Julia version. But, in the README and the documentation pages, we have mentioned that GenX currently runs on Julia 1.3. Can you check if you can see that please? Thanks for bringing up the Windows/Ubuntu issue. I have been doing all my coding on Ubuntu and mac over the last more than 10 years. So, I unfortunately don't have an idea with Windows. Most of our GenX team members also use mac. But, I'll ask some other team members of our research group, who use Windows to run through some tests and then I can do some bug-fix. Thanks for your help again. If you're okay, I might be touching base with you tomorrow and/or over this weekend, to check on some more tests.

**Comment by jiweiqi** [comment]
Thanks for looking into this.

+ Apologize for ignoring the notes of Julia version, which I thought was not critical.
+ Good to know that you are mostly use linux. I am also comfort with Linux.
+ So far, I don't have other urgent issue. You guys are doing an amazing work!

**Comment by sambuddhac** [comment]
Thank you so much !!!

**Comment by sambuddhac** [comment]
I am currently looking into this issue. Will resolve and touch base with the user/developer community

**Comment by sambuddhac** [comment]
We at the GenX team haven't yet created a user blog site or user query forum page. We'll bring it up at our group meeting tomorrow and work towards creating one soon. Right now, we're taking user feedback through the github channel, email (refer to the emails listed in README and welcome page of documentation pages), twitter e.t.c.

**Comment by sambuddhac** [comment]
At this point, I think, this is a version issue. Can you please check running on 1.3 series. Please refer to www.julialang.org on instructions to install version 1.3. You'll have to manually add the path of Julia. Let me know if you need help. I ran on versions 1.3.1, where everything works perfectly smooth, while, when I ran with version 1.5.6, I get this error. Can you please run with 1.3 series and let me know? 

We have designed GenX to run on Julia 1.3 series as of now (you can see that written in the documentation), but, our next high priority is to make it "run-able" on versions upto 1.6. Apologies for the inconvenience.

**Comment by stinsong4100** [comment]
Great to hear that upgrading julia support is on the to-do list!  It is always annoying when packages (like Julia) make updates that are not backwards compatible.  Thanks for your speedy response!
