### ISSUE TITLE
CO2 cap entered as hourly average rather than yearly sum

### ISSUE THREAD

**Issue by richardamiller** [GenXProject/GenX#314]
I find that entering the CO2 cap in CO2_cap.csv needs to be input as ((Cap in Mtons) / timesteps)  otherwise I do not get correct results on output.

Is this correct usage?

 From the documentation:

![image](https://user-images.githubusercontent.com/89880527/206096247-e4397f13-a58c-4a29-9474-10a092c676ef.png)

which seems to imply that you just input the cap in Mtons.

**Comment by richardamiller** [comment]
@sambuddhac  Thanks for your reply.

CO2Cap: 1
OperationWrapping: 1
TimeDomainReduction: 0

Hope this helps.

**Comment by sambuddhac** [comment]
Please run with both OperationWrapping and TDR set to 1 OR OperationWrapping set to 0, for the moment.

**Comment by richardamiller** [comment]
Thanks.  Seems to have fixed the problem.
