### ISSUE TITLE
eTotalCVarIn not found (in models with no storage??)

### ISSUE THREAD

**Issue by DanielNavia1** [GenXProject/GenX#34]
Hi,

Thanks for posting GenX as OpenSource, it is really a fantastic resource. I am setting up an ultra-simple model with only one zone, one CCGT power plant and onshore wind. This is just to build the simplest model to then gradually include more realistic features. My setup is Ubuntu and Clp. I have turned off all "extras" from the genx config file (ie. no CO2, no unit commitment, etc.) and accordingly only use the "required" input files for the model.

The model runs fine and an optimal solution is found (actually the status.csv is written and shows and OPTIMAL outcome). However, the code finds an error when writing the other output files and particularly cost.csv as it is apparently unable to find eTotalCVarIn in the model. My guess is this is due to the model not having any storage (I am assuming is CVarIn is the cost of charging storage devices). I attach a sample output of the GenX instance below. The output writing code is stopped there and only status.csv is written.

As a matter of fact, other elements in the optimization seem to be working fine. I did some pre-debugging deleting the references to eTotalCVarIn in write_cost.jl and the model runs fine and prints all the outputs correctly when that is done.

Not sure if this is just my setup or it may be something worth investigating. I understand most models will be run with some form of storage anyway, but I thought it may be worth mentioning it.

Best

Daniel

Sample output follows....

Configuring Solver
Loading Inputs
Reading Input CSV Files
Network.csv Successfully Read!
Load_data.csv Successfully Read!
Fuels_data.csv Successfully Read!
Generators_data.csv Successfully Read!
Generators_variability.csv Successfully Read!
CSV Files Successfully Read In From /home/daniel/Documents/ProjectGENX/GenX/Example_Systems/Daniel_Trial_Systems/Fifth_Ireland/
Generating the Optimization Model
Discharge Module
Non-served Energy Module
Investment Discharge Module
Dispatchable Resources Module
Thermal (No Unit Commitment) Resources Module
C02 Policies Module
Solving Model
Coin0506I Presolve 52560 (-17522) rows, 26284 (-1) columns and 175200 (-17522) elements
Clp0006I 0  Obj 437.43131 Primal inf 29799.729 (17520) Dual inf 790.1623 (2)
Clp0006I 487  Obj 0.34767904 Primal inf 26764.806 (8760)
[...]
Clp0006I 19185  Obj 451.22294
Clp0000I Optimal - objective value 451.22294
Coin0511I After Postsolve, objective 451.22294, infeasibilities - dual 0 (0), primal 1.1281284e-06 (3)
Coin0512I Presolved model was optimal, full model needs cleaning up
Clp0006I 0  Obj 451.22294 Primal inf 7.915044e-07 (3)
Clp0006I 3  Obj 451.22294
Clp0000I Optimal - objective value 451.22294
Clp0032I Optimal objective 451.2229419 - 19188 iterations time 1.842, Presolve 0.05
LP solved for primal
Writing Output
ERROR: LoadError: KeyError: key :eTotalCVarIn not found
Stacktrace:
 [1] write_costs(::String, ::String, ::Dict{Any,Any}, ::Dict{Any,Any}, ::JuMP.Model) at /home/daniel/.julia/packages/JuMP/YXK4e/src/JuMP.jl:936
 [2] write_outputs(::JuMP.Model, ::String, ::Dict{Any,Any}, ::Dict{Any,Any}) at /home/daniel/Documents/ProjectGENX/GenX/src/write_outputs/write_outputs.jl:70
 [3] top-level scope at /home/daniel/Documents/ProjectGENX/GenX/Example_Systems/Daniel_Trial_Systems/Fith_Ireland/Run.jl:73
 [4] include at ./boot.jl:328 [inlined]
 [5] include_relative(::Module, ::String) at ./loading.jl:1105
 [6] include(::Module, ::String) at ./Base.jl:31
 [7] include(::String) at ./client.jl:424
 [8] top-level scope at REPL[1]:1
in expression starting at /home/daniel/Documents/ProjectGENX/GenX/Example_Systems/Daniel_Trial_Systems/Fith_Ireland/Run.jl:73

**Comment by dharik13** [comment]
Thanks for pointing this out. It looks like we need to add an condition that checks to see if set "STOR_ALL" is empty or not prior to adding this term. We have submitted a pull request with the updated change (see branch "Fix-etotalCVarin-bug"). Should be reviewed and merged to main branch shortly.

**Comment by sambuddhac** [comment]
Hi Daniel, 

Thanks for bringing the issue to our notice. Thanks Dharik for helping out. The modifications have been merged to the main branch. Can you please check and see if everything works fine now? Let me know in case of a problem.

Sam

**Comment by DanielNavia1** [comment]
Hi Sam and Dharik

I have just re-run the scenario and I can confirm that it does now work without any problems. Thanks a lot.

Daniel

**Comment by sambuddhac** [comment]
Awesome !!! Thanks a lot !!! I am going to close this issue then.
