### ISSUE TITLE
data inputs "cluster" and "region" in generators_data.csv

### ISSUE THREAD

**Issue by dharik13** [GenXProject/GenX#36]
I just ran into an error while running GenX with an new case study that relates to missing column "region" in Generators_data.csv - apparently this is used in write_energy_revenue.jl. However, this column is not described in the documentation. Same for "cluster" column in Generators_data.csv

**Comment by nspatank** [comment]
User needs to add 'region' and 'cluster' columns in the input Generators_data.csv file. These columns are not used in the model but are required for writing the outputs.

region - Name of the model region
cluster - Number of the cluster when representing multiple clusters of a given technology in a given region.

More details: https://genxproject.github.io/GenX/dev/
