### ISSUE TITLE
Combining HYDRO and LDS doesn't work

### ISSUE THREAD

**Issue by gschivley** [GenXProject/GenX#361]
On the main branch, `load_inputs.is_period_map_necessary` only returns true if `OperationWrapping == 1` and `!isempty(inputs["STOR_LONG_DURATION"])`. `inputs["STOR_HYDRO_LONG_DURATION"]` is not considered.

Current code:
```julia
function is_period_map_necessary(setup::Dict, path::AbstractString, inputs::Dict)
	ow = setup["OperationWrapping"]==1
	has_stor_lds = !isempty(inputs["STOR_LONG_DURATION"])
	ow && has_stor_lds
end
```

Suggested change:
```julia
function is_period_map_necessary(setup::Dict, path::AbstractString, inputs::Dict)
	ow = setup["OperationWrapping"]==1
	has_stor_lds = !isempty(inputs["STOR_LONG_DURATION"])
	has_hydro_lds = !isempty(inputs["STOR_HYDRO_LONG_DURATION"])
	ow && (has_stor_lds || has_hydro_lds)
end
```

**Comment by cfe316** [comment]
This makes sense conceptually. I hadn't realized that an element of
STOR_HYDRO_LONG_DURATION was not also an element of STOR_LONG_DURATION. To be honest I
hadn't been thinking about Hydro.

**Comment by cfe316** [comment]
This should now have been fixed on Develop.
