### ISSUE TITLE
Path to Period_map.csv is not valid

### ISSUE THREAD

**Issue by gschivley** [GenXProject/GenX#362]
Using a Mac, the function `load_inputs.is_period_map_exist` does not return true even when a valid Period_map.csv file exists. The `path` input is modifed:
```julia
data_directory = chop(replace(path, pwd() => ""), head = 1, tail = 0)
```
But this removes the leading "/" from Mac filestrings. 

Suggested change is to use `path` instead of `data_directory`. I'm not sure if this will cause issues on other operating systems.

**Comment by cfe316** [comment]
Yes, I'm not sure why this is not just `path`.

**Comment by cfe316** [comment]
This should now be fixed on `main`. Your fix certainly worked on linux.
