### ISSUE TITLE
run_crossover type incorrect for HiGHS 1.4.3

### ISSUE THREAD

**Issue by gschivley** [GenXProject/GenX#363]
The current [GenX documentation for configuring HiGHS](https://genxproject.github.io/GenX/dev/solver_configuration/#Configuring-HiGHS) looks like this:
```
# Run the crossover routine for IPX
# [type: bool, advanced: true, range: {false, true}, default: true]
run_crossover: false #true
```

At some point it has changed from a [bool to a str](https://github.com/jump-dev/HiGHS.jl#options):
```
# Run IPM crossover: "off", "choose" or "on"
# [type: string, advanced: false, default: "on"]
run_crossover = on
```

**Comment by cfe316** [comment]
This will be fixed to #355

**Comment by cfe316** [comment]
Ok actually it doesn't fix the documentation yet, good catch

**Comment by cfe316** [comment]
This is now fixed on `main`; please update to the latest `main` version.
