### ISSUE TITLE
multi-stage TDR crashing in v0.3.4

### ISSUE THREAD

**Issue by joshdr83** [GenXProject/GenX#440]
I am having issues running the time domain reduction after upgrading to v0.3.4. My multi-stage model runs fine in v0.3.4 if I import it with the TDR_Results that I calculated using v.0.3.3. But, if I try to run the TDR in v0.3.4, it crashes:

<img width="1297" alt="image" src="https://github.com/GenXProject/GenX/assets/3343052/d6ed4bb3-7d16-4ba4-9cba-211c9814e450">

I have just imported also the `time_domain_reduction_settings.yml` that I was using in v0.3.3 -- is this not compatible with the TDR in v0.3.4? If not, is there documentation that tells me what I'd need to update?

**Comment by sambuddhac** [comment]
Thanks @joshdr83 . Will be taking a look at it soon.

**Comment by sambuddhac** [comment]
PR #442 when completed, tested satisfactorily, verified, and tested, will address this issue.

**Comment by joshdr83** [comment]
So it turns out that this issue was caused by the value of 168 being in the `Timesteps_per_Rep_Period` column of the  `load_data.csv` input files. Once this was changed to 8760, the issue went away. This 168 worked (or was ignored) in v0.3.3 and is put there via PowerGenome, so maybe that needs to be updated there? @gschivley 

![image](https://github.com/GenXProject/GenX/assets/3343052/3b076bf0-163b-42eb-b611-e6ebdad753a4)

**Comment by cfe316** [comment]
Yes - Greg has been made aware of this.
These values previously were not checked. For many cases this was not an issue, but some combinations of inputs would  lead to (silently) constructing a model which only covered the first 168 (etc) hours.

**Comment by cfe316** [comment]
This has been addressed in 0.3.5.
