### ISSUE TITLE
run_timedomainreduction! failing for multi-stage on example problems

### ISSUE THREAD

**Issue by joshdr83** [GenXProject/GenX#441]
I am running into TDR issues with the multi-stage example problems after having just updated to v0.3.4:

<img width="919" alt="image" src="https://github.com/GenXProject/GenX/assets/3343052/a688fd06-5e52-4719-8f05-d2bf46505416">

**Comment by sambuddhac** [comment]
PR #442 when completed, tested, verified, and approved, will address this issue.

**Comment by cfe316** [comment]
`run_timedomainreduction!` does not currently support multi-stage problems. I will work on upgrading it to do that.

**Comment by sambuddhac** [comment]
This should be fixed on `main` with the merge of `weekly_develop`
