### ISSUE TITLE
Storage disptach in outputs not consistent with round trip efficiency

### ISSUE THREAD

**Issue by Shubham04111** [GenXProject/GenX#459]
I am running a single zone model from example test system. After a run is completed, in the `power_balance.csv`, within the output folder, the storage dispatch must show net dispatch considering round trip efficiency(RTE) provided in the `generators_data.csv` however the maximum dispatch in the column `Storage_charge` shows maximum capacity of the storage, this is highly unlikely since RTE is mentioned in inputs. There seems to be an issue while extracting output where the storage dispatch is not consistent with RTE.

**Comment by cfe316** [comment]
Could you please provide a set of a few example values, and what you think they should be?

**Comment by dharik13** [comment]
The operational and capacity variables for charging and discharging are defined with respect to the grid. i.e. vCharge refers to the total grid electricity withdrawals from storage and not the energy actually added to the storage.  Similarly, the discharge variable refers to total electricity discharged to the grid after accounting for energy losses during discharging. Therefore, it is possible (and often commonly observed) that storage discharge and charge operational variables have maximum values equal to the charge/discharge capacity.

**Comment by cfe316** [comment]
Closing because this question was answered.
