### ISSUE TITLE
Running into errors when using CPLEX

### ISSUE THREAD

**Issue by mlozano-rmi** [GenXProject/GenX#460]
I've been trying to run some scenarios using CPLEX as a solver, but I've run into an error that I can't figure out the solution to so I'm turning here. The immediate error and stacktrace are as follows:

CPLEX Error 1028: Bad parameter name to CPLEX parameter routine.

ERROR: LoadError: CPLEX Error  1028: Bad parameter name to CPLEX parameter routine.
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] _check_ret
    @ ~/.julia/packages/CPLEX/Vd1Gd/src/MOI/MOI_wrapper.jl:119 [inlined]
  [3] set(model::CPLEX.Optimizer, param::MathOptInterface.RawOptimizerAttribute, value::Int64)
    @ CPLEX ~/.julia/packages/CPLEX/Vd1Gd/src/MOI/MOI_wrapper.jl:474
  [4] _instantiate_and_check(optimizer_constructor::MathOptInterface.OptimizerWithAttributes)
    @ MathOptInterface ~/.julia/packages/MathOptInterface/8f6oN/src/instantiate.jl:120
  [5] instantiate(optimizer_constructor::Any; with_bridge_type::Type{Float64}, with_cache_type::Nothing)
    @ MathOptInterface ~/.julia/packages/MathOptInterface/8f6oN/src/instantiate.jl:175
  [6] set_optimizer(model::JuMP.Model, optimizer_constructor::Any; add_bridges::Bool)
    @ JuMP ~/.julia/packages/JuMP/AKvOr/src/optimizer_interface.jl:361
  [7] #Model#1
    @ ~/.julia/packages/JuMP/AKvOr/src/JuMP.jl:171 [inlined]
  [8] Model
    @ ~/.julia/packages/JuMP/AKvOr/src/JuMP.jl:169 [inlined]
  [9] generate_model(setup::Dict{Any, Any}, inputs::Dict{Any, Any}, OPTIMIZER::MathOptInterface.OptimizerWithAttributes)
    @ GenX ~/Library/CloudStorage/OneDrive-RMI/Documents/GenX-main/src/model/generate_model.jl:83
[10] top-level scope
    @ ~/Library/CloudStorage/OneDrive-RMI/Documents/2030_MoreZones/100AM_2030_NMAZ_10000_1kg_v2/Run_247.jl:76
    
   
I've cross-checked the terms used in the "configure_cplex.jl" file (starting line 44: key_replacement = Dict...) with the ones used by the latest version of CPLEX (22.1.1.) (e.g., https://www.ibm.com/docs/en/icos/22.1.1?topic=cf-epopt-field) and I believe they all match. Has anyone run into this issue or have any suggestions on what else I should look into?

I'm happy to share my full process/code if it's useful. Thanks.

**Comment by sambuddhac** [comment]
@mlozano-rmi did you make sure to uncomment the pertinent CPLEX lines in the Project.toml for both the [deps] and [compat] and also uncomment the pertinent CPLEX lines in GenX.jl? Please let me know.

**Comment by sambuddhac** [comment]
Please refer to the `README` in the section on `Using Commercial solvers: Gurobi or CPLEX` as to how to run with those, if you haven't already. Please let me know if you still face issue.

**Comment by mlozano-rmi** [comment]
@sambuddhac Thank you for your reply. I did not encounter any documentation specifying changes to the Project.toml file so I appreciate your suggestion. On my version of the file (which I couldn't attach but have pasted below), all lines are uncommented.

Under [deps], am I supposed to update the CPLEX value to my API key?
Under [compat], there is no CPLEX line. Should I set the value to the version I am using? CPLEX = "22.1.1"

Again, thank you for your prompt reply!



**Project.toml code:**

name = "GenX"
uuid = "5d317b1e-30ec-4ed6-a8ce-8d2d88d7cfac"
authors = ["Jesse Jenkins", "Nestor Sepulveda", "Dharik Mallapragada", "Aaron Schwartz", "Neha Patankar", "Qingyu Xu", "Jack Morris", "Sambuddha Chakrabarti"]
version = "0.3.4"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CPLEX = "a076750e-1247-5638-91d2-ce28b192dca0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
Clp = "e2554f3b-3117-50c0-817c-e040a3ddf72d"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
CSV = "0.10.4"
Cbc = "1.0.1"
Clp = "1.0.1"
Clustering = "0.14.2"
Combinatorics = "1.0.2"
DataFrames = "1.3.4"
DataStructures = "0.18.13"
Distances = "0.10.7"
HiGHS = "1.1.4"
JuMP = "1.1.1"
MathOptInterface = "1.6.1"
RecursiveArrayTools = "2.31.2"
Statistics = "1.4.0"
StatsBase = "0.33.21"
YAML = "0.4.7"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

**Comment by sambuddhac** [comment]
I would suggest instead of modifying the Project.toml file, refer to my second reply, where I wrote, "Please refer to the `README` in the section on `Using Commercial solvers: Gurobi or CPLEX` as to how to run with those, if you haven't already. Please let me know if you still face issue." Apologies for the confusion. We are now doing things in a much cleaner way. So, you don't need to change the `Project.toml`.

**Comment by sambuddhac** [comment]
So, I could see that the `CPLEX.jl` dependency is added to your (@v1.8) pkg> environment and not `(GenX) pkg>` environment. I believe that might be why you are still facing the bug. The way to fix this would be to start the julia kernel like `julia -project=.` followed by `] instantiate` and then do a add CPLEX while still in the `(GenX) pkg>` prompt. At the end of this, before quitting the GenX environment, check your dependency list with `st` and hitting enter key. Note: PLEASE DO NOT ADD ANY LINE FOR CPLEX OR MODIFY THE Project.toml (i.e. ignore my first message).

**Comment by mlozano-rmi** [comment]
Thank you, and noted, I will not touch the Project.toml file. 

CPLEX is also added to the GenX package, as seen here:
<img width="618" alt="Screenshot 2023-05-23 at 10 52 56 AM" src="https://github.com/GenXProject/GenX/assets/130390560/cea55142-c795-44a7-8deb-f20408279712">
<img width="750" alt="image" src="https://github.com/GenXProject/GenX/assets/130390560/7f2ceb97-2cc3-4f6c-b30f-1efa006c627d">


Unfortunately I still run into the bad parameter name issue.

**Comment by mlozano-rmi** [comment]
That would be very appreciated, thank you so much! Please let me know if you need anything from me in the meantime.

**Comment by cfe316** [comment]
One way to debug here would be perform a "binary search" of all the parameters being sent to CPLEX.
Ultimately these should be coming from two sources:
the `default_settings` dictionary in `GenX/src/configure_solver/configure_cplex.jl` and the `cplex_settings.yml` file in your case.

The settings in the case should be overwriting any values with the same name in the `default_settings` dict.
Then these are renamed to things like `CPX_...` which are passed to the solver.

One thing you might try is commenting out (almost) all the lines in the default_settings dict and the cplex_settings.yml file. If that works, add half of them back in, and so on. Then we can figure out which parameters are raising the issue.

**Comment by mlozano-rmi** [comment]
@cfe316 Thank you so much for this debugging suggestion! I've actually narrowed the problem down to line 4 in cplex_setting.yml, that being

Pre_Solve: 1 # Controls presolve level.

I was able to leave the rest uncommented in both files, but including this line is what generates the error I shared. 

Frankly, I don't know what this variable is responsible for, but I tried changing the value to 0 and 2 but I still generate the error. Upon checking configure_cplex.jl, there is no key replacement for the Pre_Solve variable to a CPLEX equivalent, so perhaps the error is generated because we are importing Pre_Solve to CPLEX which does not exist. 

That being said, do you suggest removing/commenting out the Pre_Solve line, or should we find the equivalent variable in CPLEX?

Most importantly, thank you for helping me pinpoint the error! It's been driving me crazy and I'm glad to finally be making progress.

**Comment by cfe316** [comment]
Ok, yes, that would be the issue. 
Somewhat recently we refactored the way that settings were passed to the solvers.

In the past there was an "allow-list" so only specific, correctly named settings would be sent to the solver, and all others would be silently ignored. However, we believe that the user should know exactly which settings are being sent to the solver, and that if the user makes a typo, this should result in an error rather than silently ignoring the typo'd setting.

So, if your cplex_settings.yml file was copied from an earlier case, it may now have invalid settings. 
Also, our apologies if you recently copied this from an example file - we may not have scanned all the examples for this key.
Since all the CPLEX settings seem to start with `CPX`, then yes, `Pre_Solve` will throw an error. You can try looking up the correct setting. If it's something like `CPX_PRESOLVE` then you can change that line in `cplex_settings.yml`. We will work on changing this in the example files (or providing the correct translation in the `key_replacements` dict.)

Thanks again for raising this issue.

**Comment by mlozano-rmi** [comment]
I pulled the settings from one of your published 2030 scenarios, but all good, I'm glad we figured it out!

I added the following to key_replacement under configure_cplex.jl and I got through the previous error point

"Pre_Solve" => "CPX_PARAM_PRESLVND",

Here is the link to the IBM documentation for this variable: https://www.ibm.com/docs/en/icos/20.1.0?topic=parameters-node-presolve-switch

<img width="979" alt="image" src="https://github.com/GenXProject/GenX/assets/130390560/cf701c30-3a72-4c27-a19c-dde7dce0c310">

I'm glad we were able to find the breaking point! Thank you both for your help.

**Comment by cfe316** [comment]
Thank you for suggesting CPX_PARAM_PRESLVND. It looks like that's specificially for MIP problems. It looks like you might also try CPX_PARAM_PREIND.
https://www.ibm.com/docs/en/icos/12.8.0.0?topic=parameters-presolve-switch

**Comment by mlozano-rmi** [comment]
Thank you, that does seem more appropriate. 

I don't know if I should start a new thread but I had a new question:
We have purchased a license for CPLEX, but upon running the scenario, I get an error suggesting that I'm using the free Community version and not a purchased license. I have followed IBM's steps for activating the license key, but I'm wondering whether there is somewhere in the GenX code where this is happening. 

For example, in the Project.toml file, I see a bunch of values under [deps] that have the form of license keys. I tried replacing the value under CPLEX with my license key but this cause a whole new issue that caused the model to stop running much earlier. Do you have any suggestions (e.g., whether this is an issue within GenX or something on my or IBM's side)?

**Comment by cfe316** [comment]
Actually you might also need to read the instruction at https://github.com/jump-dev/CPLEX.jl . It looks like there's something about a `CPLEX_STUDIO_BINARIES` environment variable.
