### ISSUE TITLE
Maximum Capacity Requirement slack variables have wrong sign

### ISSUE THREAD

**Issue by wilson-ricks** [GenXProject/GenX#461]
In `maximum_capacity_requirement.jl`, `vMaxCap_slack` should be subtracted from `EP[:eMaxCapRes]` rather than added as it is now. The slack variable should make it easier to meet the constraint on maximum capacity by artificially reducing that capacity.

**Comment by filippopecci** [comment]
Closed as this has been fixed in [c52612f](https://github.com/GenXProject/GenX/commit/c52612ffdea1d8791eb55e9501682b0f044128d4)
