### ISSUE TITLE
Transmission losses in power_balance.csv half what they should be

### ISSUE THREAD

**Issue by Nick-Maurer** [GenXProject/GenX#476]
I've noticed in recent GenX runs that my power balance wasn't summing to zero in a given region. Looking into it further, it seems the transmission losses are written as half what they actually are (when comparing to the tlosses.csv file). In write_power_balance.jl it seems to be halved, perhaps once too many times? Just want to raise this in case anyone else has been seeing it, or maybe its a problem on my end....

**Comment by cfe316** [comment]
This has now been fixed in v0.3.6.
