### ISSUE TITLE
Startup and shutdown constraints

### ISSUE THREAD

**Issue by AshwinSandeep1** [GenXProject/GenX#477]
I was wondering if replacing constraints 2-3 in thermal_commit with the more limiting constraints I have attached would have any advantage? I would imagine this prevents the scenario where the model erroneuosly starts-up/shuts-down more units than is physically possible?
![Cycling constraints](https://github.com/GenXProject/GenX/assets/135298716/74c02173-5914-441c-880a-ec05121dba84)

**Comment by cfe316** [comment]
Ashwin looked into this further and said:

"I replaced the original constraints with the new more limiting constraints I proposed and as expected there is no real change in objective function value, no. of iterations or simulation time. So, I guess for the problems we have, it is reasonable to leave the constraints as it is. You can close that issue as well if you are happy with this info."
