### ISSUE TITLE
Check if gen data column is necessary when scaling factors

### ISSUE THREAD

**Issue by gschivley** [GenXProject/GenX#48]
`Generators_data.csv` has several columns that aren't always needed. One example is all of the `Charge_Cost` columns, which are only used if a resource is `STOR ==2`. When assembling data for a model it would be great if I could omit these columns. 

One solution would be to check if any resources have `STOR` values of 1 or 2 and then add the `MWh`/`MWhyr` or `Charge` column names to a list of all columns that need to be scaled (in [this section](https://github.com/GenXProject/GenX/blob/804e63eedc5dec917439ee687dcb601edaa9861f/src/load_inputs/load_generators_data.jl#L93-L150)). 

If someone gives me a general guide for how to do this in Julia I can try to implement and submit a PR.

There might be some broader implications for the `NEW/RET_CAP_CHARGE/ENERGY` lines [here](https://github.com/GenXProject/GenX/blob/804e63eedc5dec917439ee687dcb601edaa9861f/src/load_inputs/load_generators_data.jl#L74-L81) -- I haven't followed the code to see where `inputs_gen` goes yet.

**Comment by xuqingyu** [comment]
Hi Greg, I would suggest leave the generator_data.csv this way. charge cost for example will also be used for FLEX. The columns listed in the data is already the most compact set, I believe. 
Again, the tricky thing is that someone might pick these columns for their own usage in the future. 
Let me know if I can close this issue.

**Comment by sambuddhac** [comment]
Seems this issue can be closed. For the moment we agree to keep these extra columns.
