### ISSUE TITLE
storage_all.jl (Lines 143, 171)

### ISSUE THREAD

**Issue by AshwinSandeep1** [GenXProject/GenX#484]
Shouldn't the constraint on charging energy given by lines 143 and 171 be also included in the !isempty(STOR_RSV_ONLY) and !isempty(STOR_NO_RES) scenarios (analogous to the constraints on discharging energy). Currently this constraint does not seem to exist for these cases.

**Comment by gmantegna** [comment]
Clarified misunderstanding via email.
