### ISSUE TITLE
Help on ReadMe Overview: SmallNewEngland\OneZone case produces following error 

### ISSUE THREAD

**Issue by BPBartholomew** [GenXProject/GenX#500]
Hi, just following the ReadMe instructions and no issue with steps 1-7 but getting the following error on step 8. Can you help?

Generating the Optimization Model
ERROR:   getOptionIndex: Option "simplex_dualise_strategy" is unknown
ERROR: LoadError: MathOptInterface.UnsupportedAttribute{MathOptInterface.RawOptimizerAttribute}: Attribute MathOptInterface.RawOptimizerAttribute("simplex_dualise_strategy") is not supported by the model.

**Comment by rowry38** [comment]
Hi, I am also getting the same error message on step 8. I have adjusted the highs settings under simplex_dualise_strategy  and this makes no difference.
The below is the status.
Project GenX v0.3.5
Status `~/GenX/Project.toml`
  [336ed68f] CSV v0.10.11
  [9961bab8] Cbc v1.1.1
  [e2554f3b] Clp v1.0.3
  [aaaa29a8] Clustering v0.15.4
  [861a8166] Combinatorics v1.0.2
  [a93c6f00] DataFrames v1.6.1
  [864edb3b] DataStructures v0.18.14
  [b4f34e82] Distances v0.10.9
  [87dc4568] HiGHS v1.5.2
  [4076af6c] JuMP v1.13.0
  [b8f27783] MathOptInterface v1.18.0
  [731186ca] RecursiveArrayTools v2.38.7
  [2913bbd2] StatsBase v0.34.0
  [ddb6d928] YAML v0.4.9
  [ade2ca70] Dates
  [37e2e46d] LinearAlgebra
  [9a3f8284] Random
  [10745b16] Statistics v1.9.0

**Comment by cfe316** [comment]
This has now been fixed: see the v0.3.6 release.

**Comment by BPBartholomew** [comment]
Belated thank you!
