### ISSUE TITLE
Up_time/Down_time > = hours_per_subperiod.

### ISSUE THREAD

**Issue by dharik13** [GenXProject/GenX#51]
I came across a modeling bug  when modeling thermal generators with Up_time/Down_time >= hours_per_subperiod for each representative period. In this case, the implemented minimum up and down time constraints look at commitment status of thermal generators in subsequent periods rather than in the same period. This results in the model reporting a key error for the last period.

I think we should update the documentation and tell the user they must use longer subperiods than the longest min up/down time if modeling UC

**Comment by sambuddhac** [comment]
Updated documentation mentioning this in the Dev branch.
