### ISSUE TITLE
"Min_Retired_Cap_MW" Behaving Badly

### ISSUE THREAD

**Issue by bpierpont** [GenXProject/GenX#514]
Bug report!

In multi-stage models, "Min_Retired_Cap_MW" is getting multiplied by the number of stages. So if the parameter has a value of 100 in stage 2, the model will use a constraint of 200. In stage 5, it would turn an input of 100 into a constraint of 500.

The problem appears to be in lines 80-84 of "src/multi_stage/endogenous_retirement.jl", where it sums the current stage's value of this parameter over the number of stages (rather than summing this parameter across stages). I'm guessing lines 135 and 184 of that file have similar issues but I haven't tested it.

**Comment by cfe316** [comment]
This is now fixed on `develop`.
