### ISSUE TITLE
Need to check for the necessary flag

### ISSUE THREAD

**Issue by nspatank** [GenXProject/GenX#535]
We need to check if the reserves flag is ON before prompting the user to add 'Reg_Cost' or 'Rsv_Cost' columns in the Generators_data file.

**Comment by cfe316** [comment]
Is the issue that the run fails without those columns, even when `Reserves=0`?

**Comment by nspatank** [comment]
Yes, that is correct.

**Comment by cfe316** [comment]
I'm not seeing this behavior on the SmallNewEngland/OneZone example: I can run without those columns just fine. Could you suggest a case where the failure occurs?

**Comment by nspatank** [comment]
Try turning ON parameter scaling.

**Comment by cfe316** [comment]
`ParameterScale` is already `1` in both of these examples. Can I ask what branch you're using? Would you be able to email me a test case?

**Comment by cfe316** [comment]
Closing issue - problem was due to old GenX version
