### ISSUE TITLE
GenX startup instructions may be able to be simplified

### ISSUE THREAD

**Issue by cfe316** [GenXProject/GenX#54]
Minimizing friction for new users is good. 
Recently I was playing around with trying to get GenX to run example cases external to the GenX directory (so that the git status remains unchanged and so I'm more confident that I'm not going to break something). I realized that the instructions

```
~ > cd GenX
~ > julia --project="GenX"
(GenX) pkg> activate .
```
are somewhat confusing and that as written, the second line's command is superfluous. Specifically, step 2 of Method 1 in the readme says that after starting julia "You will see that you're already within the (GenX) environment.". However, this is not really true. If you type `(GenX) pkg> st` you'll see that the project loader thinks it has an empty project, which just happens to be named GenX:

```
(GenX) pkg> st
      Status `~/GenX/GenX/Project.toml` (empty project)
```
it's not till you type `activate .` that the correct `toml` file is loaded.

Solutions / other information gleaned
-------------------------------------------------
Here's a few way to start a julia REPL with in the correct environment. These assume my installation is in `~/GenX`. Basically, you can use `--project=[...]` from the shell or `pkg > activate [...]` from a REPL; as far as I can tell they do the same thing. See also https://bkamins.github.io/julialang/2020/05/10/julia-project-environments.html .

### Three lines
```
~ > cd GenX
~/GenX > julia
]
(@v1.6) pkg > activate .
```

### Two lines:
```
~ > cd GenX
~/GenX > julia --project=.
```
or
```
~ > julia
]
(@v1.6) pkg > activate GenX
```
or
```
/any/directory > julia
]
(@v1.6) pkg > activate /path/to/my/GenX
```
note that you can't `activate ~/GenX` because the `~` does not get expanded.
 

### One line:
```
~ > julia --project=GenX
```
or 
```
/any/directory > julia --project=/path/to/my/GenX
````

**Comment by sambuddhac** [comment]
The latest PR and merging to the Dev branch addresses this issue. It will be merged with the main branch shortly. Closing this issue.
