### ISSUE TITLE
There's an issue when the CO2 cap is set to 2, but the file "generator_data.csv" does not have storage.

### ISSUE THREAD

**Issue by fc4uk** [GenXProject/GenX#541]
There is a bug related to the CO2 cap being set to 2 when there's no storage in the system. This issue can be reproduced in the smallnewengland/onezone directory by removing the "battery" row from generator_data.csv. Below is the error message I encountered:

`ERROR: LoadError: KeyError: key :eELOSSByZone not found`

**Comment by cfe316** [comment]
This could be solved using a line near the top of generate_model.jl

`create_empty_expression!(EP, :eELOSSByZone, Z)`

and then changing the line that constructs the entries for this `storage_all.jl` to use `add_to_expression!`.

**Comment by cfe316** [comment]
This is now fixed on `develop`.
