### ISSUE TITLE
(Internal development:) use a function to calculate locational marginal prices

### ISSUE THREAD

**Issue by cfe316** [GenXProject/GenX#557]
Many times in various write_output functions, the value

`dual.(EP[:cPowerBalance])./inputs["omega"]*scale_factor`

is computed. It would be great to put this in a function

```
function locational_marginal_prices(EP, inputs, setup)
```
that returns some data structure (Matrix? DataFrame?) of prices. Potentially it would be even better if this calculation were cached somehow.

This could make several output functions simpler and easier to understand.

**Comment by cfe316** [comment]
Well of course that function writes them, but I think it would be much more useful to separate calculating and writing, in order to not have to pass `dfPrice` back to many other `write_xxx` functions (and then navigate getting data out of that dataframe).

**Comment by xuqingyu** [comment]
Ah, I think I have done that in my branch. If anyone of you actually is working on removing dfPrice from each writing_xxx, check my branch out for an example.

**Comment by xuqingyu** [comment]
My branch is Dev_newCO2

**Comment by cfe316** [comment]
This is now completed.
