### ISSUE TITLE
Electrolyzers should report their electricity use by zone in power_balance

### ISSUE THREAD

**Issue by cfe316** [GenXProject/GenX#559]
In write_power_balance.jl, all electrolyzers report their power consumption as if it were in every zone.

```
		if (!isempty(ELECTROLYZER))
			powerbalance[(z-1)*L+11, :] = (-1) * sum(value.(EP[:vUSE][ELECTROLYZER, :].data), dims = 1)
		end
```

need something like ` ELECTROLYZER_ZONE = intersect(dfGen[dfGen.Zone.==z, :R_ID], ELECTROLYZER)`.

**Comment by cfe316** [comment]
This is now fixed on `develop`.

**Comment by sambuddhac** [comment]
PR #596 fixed this on `develop` branch
