### ISSUE TITLE
HYDRO resources cannot have different REG/RSV classes

### ISSUE THREAD

**Issue by cfe316** [GenXProject/GenX#561]
If some HYDRO resources have different values of
`(Reg_Max > 0, Rsv_Max > 0)`
than other HYDRO resources, then `hydro_res_reserves!` tries to create multiple constraints all called `cRegulation`, for example. This is not allowed by `JuMP`, so GenX errors out.

This can be fixed by
* removing these constraint names
or, if their duals are needed for some output,
* creating per-resource constraint names programmatically.

**Comment by cfe316** [comment]
`cRegulation`, `cMaxReservesUp`, `cMaxReservesDown` and `cReserves` are never referenced after creation, so these constraints can be anonymized.

**Comment by cfe316** [comment]
This would be fixed by #562 .

**Comment by sambuddhac** [comment]
This is fixed on `develop` by merge of PR #562
