### ISSUE TITLE
Unmet reserves are not output correctly

### ISSUE THREAD

**Issue by cfe316** [GenXProject/GenX#575]
`write_rsv.jl` has `unmet_vec[RSV] = value.(EP[:vUNMET_RSV][RSV])`
where `RSV = inputs["RSV"]`
but `vUNMET_RSV` is a 1D array indexed by time, not generator / `R_ID`.

**Comment by sambuddhac** [comment]
This is now fixed on `develop` with this code modification

```
rsv[RSV, :] = value.(EP[:vRSV][RSV, :]) * scale_factor
unmet_vec = value.(EP[:vUNMET_RSV]) * scale_factor
```

@cfe316 Jacob and @JesseJenkins ... I think this issue is good to be closed now?

**Comment by cfe316** [comment]
Yes, we can close it.
