### ISSUE TITLE
General Large-Scale Data for Model Input Files

### ISSUE THREAD

**Issue by jmk6102** [GenXProject/GenX#587]
Hello GenX Team, 

I am working with Dr. Eric Hittinger at RIT on a capstone project where we are looking to utilize the GenX system in our research. We are looking to use GenX to generate hourly electricity prices for each U.S. ISO (about every 5 years) into the future; 2027, 2032, 2037, etc. We were wondering if there are some input files with generic expansion inputs for the model that will help us develop these prices because we unfortunately do not have bandwidth to create all the necessary inputs for load, network, generation, etc. Or is there a dataset of predicted prices already created with the model that we could utilize and additionally cite in our research?

Thanks for your assistance!

**Comment by gschivley** [comment]
Hi @jmk6102. [PowerGenome](https://github.com/PowerGenome/PowerGenome) is the easiest way to construct GenX inputs. Even a generic system has many embedded decisions and input assumptions, so you'll need to provide a little more detail about what types of regional aggregation, technologies, policies, etc you would like to work with. Here are a few pointers for a starting place:

- We typically start from the 64 regions in [EPA's Integrated Planning Model](https://github.com/PowerGenome/PowerGenome/wiki/Geospatial-Mappings#ipm-regions). These are [aggregated into model regions](https://github.com/PowerGenome/PowerGenome/wiki/Creating-Model-Regions). We been working with a 26-zone national system recently but you can also do individual parts of the country. Or something like a detailed system of NYISO that includes all of ISONE as a single zone and PJM as a handful of zones to reflect imports/exports.
- Are you including RPS/CES policies? They are currently constructed by hand, but we're working to automate the process (or at least make it easier).
- Are there any other policies that you want to include, like IRA tax credits and minimum offshore wind capacity? Or generic carbon caps?
- Our default demand profiles are built up using scenarios of heat pump/EV stocks (plus other end-uses that are being electrified). With the underlying data it's also easy to include those end-use categories as flexible demand technologies that can shift by a few hours. We have some default assumptions from an NREL report about how much of the load can shift and by how much.
- Are you ok with default new-build technology costs and performance in NREL ATB? It is possible to include things like hydrogen turbines (we usually assume a 10% premium on top of a NG turbine) and other technologies but you will need to supply your own cost/performance data.


So even with a generic decision you'll need to decide what policies to include and what sort of spatial/temporal resolution you want to work with. Including more detail and a larger geographic scope will make run-times longer. I can help with getting set up once you decide what the systems should look like.

**Comment by jmk6102** [comment]
Hi @gschivley! Thank you for your response we appreciate all the information and have been able to discuss and determine what we would like to do moving forward. 

- Taking a look at the 26-zone system this would certainly fit our needs. Our initial thought is to simplify the zones to be as close to the 10 traditional U.S. ISO zones (all 7 ISO's, Northwest, Southwest & Southeast) as possible. From the IPM map it seems as though we could get pretty close to this setup. If I understand correctly creating new model regions will only incur necessary updates for `model_regions` and `region_aggregations` parameters. Does the `cost_multiplier_region_map` need to be updated with each zoning model?
- In the realm of policy we are only looking at generic carbon reduction as follows:
    -40% carbon reduction by 2030
    -75% carbon reduction by 2040
    -100% carbon reduction by 2050
- The default demand profiles and new-build costs will work great for our purposes. 

I believe that I have PowerGenome setup on my system at this time and could use some guidance moving forward to create the appropriate model for our purposes.

**Comment by jmk6102** [comment]
HI again @gschivley. I wanted to reach back out to see if you are still able to assist with this. 
We have made some overall system decisions but are still looking for assistance in translating this to PowerGenome and then to GenX.
Thanks!

**Comment by gschivley** [comment]
Hi @jmk6102, sorry this fell off my plate. We do already have a 26-zone system that is probably close to what you need. Let me figure out a good place to share it (and other template systems) publicly.

> If I understand correctly creating new model regions will only incur necessary updates for model_regions and region_aggregations parameters. Does the cost_multiplier_region_map need to be updated with each zoning model?

There are a number of potential settings and data inputs that need to be updated. `model_regions` and `region_aggregations` are the first place to start. `cost_multiplier_region_map` might also need to be updated. `renewables_clusters` will quite likely need to be updated, and you'll need to be sure the resource group data files with wind/solar interconnection costs are also at the correct level of aggregation for your system. `regional_hydro_factor` and `energy_storage_duration` may also need to be updated with new region aggregations/names. Same with `aeo_fuel_region_map`. The policy files (CO₂ caps and RPS/CES constraints) also have region names in them.

There might be a couple other places but I think that covers most of it.

**Comment by jmk6102** [comment]
@gschivley That would be great, thank you for finding a way to share that system with us.

Also, thank you for clearing some things up with my questions.

**Comment by sambuddhac** [comment]
This has been responded to and good to be closed.
