### ISSUE TITLE
GenX takes extremely long time to write some output files when running 52-wk case

### ISSUE THREAD

**Issue by qluo0320github** [GenXProject/GenX#607]
When running a 52-wk case, GenX took long time to write some files: storage duals/ fuel consumption/ (0.8 hrs); commitment/starup/shutdown (1 hr); co2 (2 hours); capacity value (6 hrs). 

The total time to finish the case is about 24 hours.

**Comment by sambuddhac** [comment]
@qluo0320github under testing right now !!!

**Comment by lbonaldo** [comment]
After conducting additional tests on both the `main` and `develop` branches, using various versions of Julia, JuMP, and the solver, we have determined that the code functions as expected. To optimize performance, we recommend the following setup:
- Julia >= 1.9
- JuMP >= 1.19

We will continue to monitor the output writing functions and reopen the issue if necessary.
