### ISSUE TITLE
Multi-stage myopic stats file is empty

### ISSUE THREAD

**Issue by gschivley** [GenXProject/GenX#636]
The multi-stage output file stats_multi_stage.csv does not have stats on each stage when running in myopic mode (the file does have valid information in foresight). Each of the stage result folders (Results_p1, etc) does have a valid status.csv.

**Comment by filippopecci** [comment]
Yes this happens because that file reports the iteration data (Upper bound, lower bound and optimality gap) of the DDP algorithm when solving the case with perfect foresight. We should probably avoid creating the file in myopic, because there is no information to print in this case.

**Comment by sambuddhac** [comment]
Merging of PR #617 on `develop` addresses this
