### ISSUE TITLE
Project.toml on dev branch does not have Gurobi/CPLEX info

### ISSUE THREAD

**Issue by cfe316** [GenXProject/GenX#77]
Maybe these got deleted?

Info

#CPLEX = "a076750e-1247-5638-91d2-ce28b192dca0"
#Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"

```
[compat]
#CPLEX = "0.7.7"
#Gurobi = "0.9.14"
```

**Comment by sambuddhac** [comment]
Resolved !!!
