### ISSUE TITLE
Loading of files can be simplified by using joinpath

### ISSUE THREAD

**Issue by cfe316** [GenXProject/GenX#79]
By constructing paths to CSV files using the built-in function `joinpath`  (which returns a `String)` we can remove the `sep` variable and its being passed as an argument to each `load_xxx` function. This makes the code simpler.

**Comment by gschivley** [comment]
Looks like this is now addressed in #97 (but I don't have permission to link).

**Comment by cfe316** [comment]
Yup, I forgot to link them.

**Comment by cfe316** [comment]
This is also addressed by #104 .
