### ISSUE TITLE
Unable to install required packages

### ISSUE THREAD

**Issue by richardamiller** [GenXProject/GenX#82]
Attempting a clean install of GenX and Julia on December 9th 2021.

When I attempt to initiate Julia to work with  GenX I get the following error when trying to install the required packages with instantiate:

![image](https://user-images.githubusercontent.com/89880527/145284546-1668d197-c73f-47f9-8c9b-007532919679.png)

**Comment by ASamarkRoth** [comment]
I had a similar issue. Maybe this can help you: https://github.com/GenXProject/GenX/issues/81

**Comment by sambuddhac** [comment]
Thanks @ASamarkRoth .... I am pasting the earlier message here once again:

Thanks for bringing the issue to our notice. Please try deleting the Manifest.toml and then do a fresh run of Project.toml.

Also, changing just the version number of JuMP isn't enough, you'll also need to change the uuid. That is, you'll need to update both the [deps] and the [compat] in the Project.toml. The easiest way to do so, is to update the version number in julenv.jl file, and run GenX using the method 2 (refer to the README instructions) and then, refer to the Project.toml inside the GenXJulEnv folder within the particular example case folder you just ran using Method 2, to get the uuid for the new JuMP version.

Subsequently, use that uuid in the generic Project.toml and then do a run with Method 1. This will generate the new Manifest.toml and also run GenX smoothly.

Let me know, if this works and/or if you need further help.

Sam
