### ISSUE TITLE
Turning on OperationWrapping = 1 leads to large amounts of non-served energy in full-year examples

### ISSUE THREAD

**Issue by cfe316** [GenXProject/GenX#95]
To reproduce, 

Turn OperationWrapping = 1 in the SmallNewEngland/OneZone example, and examine the resulting power_balance.csv. It appears that there are large amounts of NSE. 

Wilson suggested that for some reason with OperationWrapping on the NSE costs were not being properly accounted. I haven't looked into this yet, but he suggested it's because this is a full year problem.

**Comment by dharik13** [comment]
Is this resolved or still a problem?

**Comment by sambuddhac** [comment]
Resolved !!!
